import type { Metadata } from "next";
import "@/app/globals.css";
import { Providers } from "../Providers";
import { Mousefollow } from "../components";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Can be imported from a shared config
const locales = ['en', 'es'];
 
export function generateStaticParams() {
  return locales.map((locale) => ({locale}));
}

export default function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string }
}>) {
  return (
    <html lang={ locale } suppressHydrationWarning>
      <body className="dark:bg-slate-900">
        <Providers>
          {children}
          <Mousefollow/>
        </Providers>
      </body>
    </html>
  );
}
